# Generated by Django 6.0.4 on 2026-04-30 00:15

from django.db import migrations

def create_role(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    Group.objects.get_or_create(name='user')
    Group.objects.get_or_create(name='admin')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(create_role),
    ]
